// This file is generated by Nord.js
// Do not edit this file directly
import type { Manifest } from "nordjs";
import get_date from "./routes/date/get";
import get_health from "./routes/health/get";

export const routes: Manifest = {
  get_health: {
    method: "get",
    path: "/health/get.ts",
    route: get_health,
  },
  get_date: {
    method: "get",
    path: "/date/get.ts",
    route: get_date,
  },
};
