name: Build CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Build on Node.js v16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        shell: bash
        run: node common/scripts/install-run-rush.js install
      - name: Build all packages
        shell: bash
        run: node common/scripts/install-run-rush.js build
