name: Docs CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Build
        shell: bash
        run: npm run docs:build
      - name: Copy static files
        shell: bash
        run: cp -r docs/assets docs/.vitepress/dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: docs/.vitepress/dist
          cname: nord.js.org
